# Capstone Project Day 1 -  Understanding Data

In [1]:
# Cell 1 — Project Setup
import pandas as pd
import requests
import json
from pathlib import Path

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

In [2]:
# Cell 2 — Paths
# Since notebooks run differently from scripts, avoid __file__.

from pathlib import Path

BASE_DIR = Path.cwd().parent

RAW_DIR   = BASE_DIR / "data" / "raw"
LIVE_DIR  = BASE_DIR / "data" / "live_nav"
REPORT_DIR = BASE_DIR / "reports"

LIVE_DIR.mkdir(exist_ok=True)
REPORT_DIR.mkdir(exist_ok=True)

print(BASE_DIR)

C:\Users\Sai Khedekar\Desktop\CapstoneProject_1

In [3]:
# Cell 3 — Dataset Registry
datasets = {
    "fund_master":   "01_fund_master.csv",
    "nav_history":   "02_nav_history.csv",
    "aum":           "03_aum_by_fund_house.csv",
    "sip":           "04_monthly_sip_inflows.csv",
    "category":      "05_category_inflows.csv",
    "folio":         "06_industry_folio_count.csv",
    "performance":   "07_scheme_performance.csv",
    "transactions":  "08_investor_transactions.csv",
    "portfolio":     "09_portfolio_holdings.csv",
    "benchmark":     "10_benchmark_indices.csv"
}

In [9]:
# Cell 4 — Load All Datasets
loaded_data = {}

for name, file in datasets.items():

    df = pd.read_csv(RAW_DIR / file)

    loaded_data[name] = df

    print("\n" + "="*60)
    print(name.upper())
    print("="*60)

    print("Shape :", df.shape)
    print("")
    display(df.head())

============================================================
FUND_MASTER
============================================================
Shape : (40, 15)

Datatypes:
amfi_code               int64
fund_house                str
scheme_name               str
category                  str
sub_category              str
plan                      str
launch_date               str
benchmark                 str
expense_ratio_pct     float64
exit_load_pct         float64
min_sip_amount          int64
min_lumpsum_amount      int64
fund_manager              str
risk_category             str
sebi_category_code        str
dtype: object

,amfi_code,fund_house,scheme_name,category,sub_category,plan,launch_date,benchmark,expense_ratio_pct,exit_load_pct,min_sip_amount,min_lumpsum_amount,fund_manager,risk_category,sebi_category_code
0,119551,SBI Mutual Fund,SBI Bluechip Fund - Regular Plan - Growth,Equity,Large Cap,Regular,2006-02-14,NIFTY 100 TRI,1.54,1.0,500,1000,Sohini Andani,Moderate,EC01
1,119552,SBI Mutual Fund,SBI Bluechip Fund - Direct Plan - Growth,Equity,Large Cap,Direct,2013-01-01,NIFTY 100 TRI,0.66,1.0,500,1000,Sohini Andani,Moderate,EC01
2,119598,SBI Mutual Fund,SBI Small Cap Fund - Regular Plan - Growth,Equity,Small Cap,Regular,2009-09-09,BSE 250 SmallCap TRI,1.43,1.0,500,1000,R. Srinivasan,Very High,EC03
3,119599,SBI Mutual Fund,SBI Small Cap Fund - Direct Plan - Growth,Equity,Small Cap,Direct,2013-01-01,BSE 250 SmallCap TRI,0.72,1.0,500,1000,R. Srinivasan,Very High,EC03
4,119120,SBI Mutual Fund,SBI Magnum Gilt Fund - Regular Plan - Growth,Debt,Gilt,Regular,2000-12-30,CRISIL Dynamic Gilt Index,0.77,0.0,500,1000,Dinesh Ahuja,Low,DC02

============================================================
NAV_HISTORY
============================================================
Shape : (46000, 3)

Datatypes:
amfi_code      int64
date             str
nav          float64
dtype: object

   amfi_code        date      nav
0     119551  2022-01-03  54.3856
1     119551  2022-01-04  54.3474
2     119551  2022-01-05  54.6869
3     119551  2022-01-06  55.4550
4     119551  2022-01-07  55.3692

============================================================
AUM
============================================================
Shape : (90, 5)

Datatypes:
date                  str
fund_house            str
aum_lakh_crore    float64
aum_crore           int64
num_schemes         int64
dtype: object

         date           fund_house  aum_lakh_crore  aum_crore  num_schemes
0  2022-03-31      SBI Mutual Fund            6.05     605000          186
1  2022-03-31  ICICI Prudential MF            4.65     465000          216
2  2022-03-31     HDFC Mutual Fund            4.35     435000          195
3  2022-03-31      Nippon India MF            2.70     270000          177
4  2022-03-31    Kotak Mahindra MF            2.70     270000          168

============================================================
SIP
============================================================
Shape : (48, 6)

Datatypes:
month                            str
sip_inflow_crore               int64
active_sip_accounts_crore    float64
new_sip_accounts_lakh        float64
sip_aum_lakh_crore           float64
yoy_growth_pct               float64
dtype: object

,month,sip_inflow_crore,active_sip_accounts_crore,new_sip_accounts_lakh,sip_aum_lakh_crore,yoy_growth_pct
0,2022-01,11517,4.91,9.10,4.80,NaN
1,2022-02,11438,4.93,8.20,4.85,NaN
2,2022-03,12328,5.09,10.50,5.01,NaN
3,2022-04,11863,5.48,9.52,5.12,NaN
4,2022-05,12286,5.55,8.10,5.15,NaN

============================================================
CATEGORY
============================================================
Shape : (144, 3)

Datatypes:
month                   str
category                str
net_inflow_crore    float64
dtype: object

     month         category  net_inflow_crore
0  2024-04        Large Cap            2413.0
1  2024-04          Mid Cap            3897.0
2  2024-04        Small Cap            3533.0
3  2024-04        Flexi Cap            4947.0
4  2024-04  Large & Mid Cap            4214.0

============================================================
FOLIO
============================================================
Shape : (21, 6)

Datatypes:
month                      str
total_folios_crore     float64
equity_folios_crore    float64
debt_folios_crore      float64
hybrid_folios_crore    float64
others_folios_crore    float64
dtype: object

,month,total_folios_crore,equity_folios_crore,debt_folios_crore,hybrid_folios_crore,others_folios_crore
0,2022-01,13.26,9.28,1.86,0.80,1.33
1,2022-04,13.91,9.74,1.95,0.83,1.39
2,2022-07,13.85,9.69,1.94,0.83,1.38
3,2022-10,14.12,9.88,1.98,0.85,1.41
4,2023-01,14.81,10.37,2.07,0.89,1.48

============================================================
PERFORMANCE
============================================================
Shape : (40, 19)

Datatypes:
amfi_code               int64
scheme_name               str
fund_house                str
category                  str
plan                      str
return_1yr_pct        float64
return_3yr_pct        float64
return_5yr_pct        float64
benchmark_3yr_pct     float64
alpha                 float64
beta                  float64
sharpe_ratio          float64
sortino_ratio         float64
std_dev_ann_pct       float64
max_drawdown_pct      float64
aum_crore               int64
expense_ratio_pct     float64
morningstar_rating      int64
risk_grade                str
dtype: object

,amfi_code,scheme_name,fund_house,category,plan,return_1yr_pct,return_3yr_pct,return_5yr_pct,benchmark_3yr_pct,alpha,beta,sharpe_ratio,sortino_ratio,std_dev_ann_pct,max_drawdown_pct,aum_crore,expense_ratio_pct,morningstar_rating,risk_grade
0,119551,SBI Bluechip Fund - Regular Plan - Growth,SBI Mutual Fund,Large Cap,Regular,12.42,12.36,14.45,11.49,0.87,0.89,0.88,1.29,14.0,-21.70,14288,1.54,4,Moderate
1,119552,SBI Bluechip Fund - Direct Plan - Growth,SBI Mutual Fund,Large Cap,Direct,15.25,11.30,14.23,9.52,1.78,0.87,0.81,1.29,14.0,-24.43,1231,0.66,3,Moderate
2,119598,SBI Small Cap Fund - Regular Plan - Growth,SBI Mutual Fund,Small Cap,Regular,24.56,23.39,20.67,22.16,1.23,0.89,0.94,1.35,25.0,-13.35,19259,1.43,5,Very High
3,119599,SBI Small Cap Fund - Direct Plan - Growth,SBI Mutual Fund,Small Cap,Direct,20.59,23.14,21.82,22.01,1.13,1.04,0.93,1.67,25.0,-24.78,36061,0.72,4,Very High
4,119120,SBI Magnum Gilt Fund - Regular Plan - Growth,SBI Mutual Fund,Gilt,Regular,5.34,6.07,5.43,4.47,1.60,0.22,1.52,2.11,4.0,-2.30,24101,0.77,5,Low

============================================================
TRANSACTIONS
============================================================
Shape : (32778, 13)

Datatypes:
investor_id               str
transaction_date          str
amfi_code               int64
transaction_type          str
amount_inr              int64
state                     str
city                      str
city_tier                 str
age_group                 str
gender                    str
annual_income_lakh    float64
payment_mode              str
kyc_status                str
dtype: object

,investor_id,transaction_date,amfi_code,transaction_type,amount_inr,state,city,city_tier,age_group,gender,annual_income_lakh,payment_mode,kyc_status
0,INV003054,2024-01-01,119092,SIP,1834,Telangana,Hyderabad,T30,56+,Female,77.1,UPI,Verified
1,INV002952,2024-01-01,148567,Redemption,392882,Punjab,Amritsar,B30,18-25,Male,7.1,Cheque,Verified
2,INV003420,2024-01-01,118636,SIP,912,Haryana,Faridabad,B30,36-45,Male,47.2,Mandate,Verified
3,INV003436,2024-01-01,118634,SIP,1102,Maharashtra,Mumbai,T30,36-45,Female,54.4,Cheque,Pending
4,INV004691,2024-01-01,119094,Lumpsum,8682,Delhi,Noida,T30,26-35,Male,14.5,Net Banking,Pending

============================================================
PORTFOLIO
============================================================
Shape : (322, 8)

Datatypes:
amfi_code              int64
stock_symbol             str
stock_name               str
sector                   str
weight_pct           float64
market_value_cr      float64
current_price_inr    float64
portfolio_date           str
dtype: object

,amfi_code,stock_symbol,stock_name,sector,weight_pct,market_value_cr,current_price_inr,portfolio_date
0,119551,POWERGRID,Power Grid Corporation,Utilities,13.85,737.09,6011.08,2025-12-31
1,119551,HDFCBANK,HDFC Bank Ltd,Banking,11.19,88.97,1074.65,2025-12-31
2,119551,GRASIM,Grasim Industries Ltd,Diversified,9.90,208.45,5964.59,2025-12-31
3,119551,DRREDDY,Dr. Reddy's Laboratories,Pharma,4.76,161.32,3748.82,2025-12-31
4,119551,ASIANPAINT,Asian Paints Ltd,Paints,10.25,725.90,1321.45,2025-12-31

============================================================
BENCHMARK
============================================================
Shape : (8050, 3)

Datatypes:
date               str
index_name         str
close_value    float64
dtype: object

         date index_name  close_value
0  2022-01-03    NIFTY50     17492.79
1  2022-01-04    NIFTY50     17689.64
2  2022-01-05    NIFTY50     17835.05
3  2022-01-06    NIFTY50     17878.51
4  2022-01-07    NIFTY50     17759.15

In [10]:
# Cell 5 — Dataset Summary Report
summary = []

for name, df in loaded_data.items():

    summary.append({
        "Dataset":        name,
        "Rows":           df.shape[0],
        "Columns":        df.shape[1],
        "Missing Values": df.isnull().sum().sum(),
        "Duplicates":     df.duplicated().sum()
    })

summary_df = pd.DataFrame(summary)

summary_df

        Dataset   Rows  Columns  Missing Values  Duplicates
0   fund_master     40       15               0           0
1   nav_history  46000        3               0           0
2           aum     90        5               0           0
3           sip     48        6              12           0
4      category    144        3               0           0
5         folio     21        6               0           0
6   performance     40       19               0           0
7  transactions  32778       13               0           0
8     portfolio    322        8               0           0
9     benchmark   8050        3               0           0

In [11]:
# Cell 6 — Save Summary
summary_df.to_csv(
    REPORT_DIR / "dataset_summary.csv",
    index=False
)

print("Dataset summary saved")

Dataset summary saved

In [12]:
# Cell 7 — Dataset Information
for name, df in loaded_data.items():

    print("\n" + "="*60)
    print(name.upper())
    print("="*60)

    print("\nData Types")
    print(df.dtypes)

    print("\nMissing Values")
    print(df.isnull().sum())

    print("\nDuplicates")
    print(df.duplicated().sum())

============================================================
FUND_MASTER
============================================================

Data Types
amfi_code               int64
fund_house                str
scheme_name               str
category                  str
sub_category              str
plan                      str
launch_date               str
benchmark                 str
expense_ratio_pct     float64
exit_load_pct         float64
min_sip_amount          int64
min_lumpsum_amount      int64
fund_manager              str
risk_category             str
sebi_category_code        str
dtype: object

Missing Values
amfi_code             0
fund_house            0
scheme_name           0
category              0
sub_category          0
plan                  0
launch_date           0
benchmark             0
expense_ratio_pct     0
exit_load_pct         0
min_sip_amount        0
min_lumpsum_amount    0
fund_manager          0
risk_category         0
sebi_category_code    0
dtype: int64

Duplicates
0

============================================================
NAV_HISTORY
============================================================

Data Types
amfi_code      int64
date             str
nav          float64
dtype: object

Missing Values
amfi_code    0
date         0
nav          0
dtype: int64

Duplicates
0

============================================================
AUM
============================================================

Data Types
date                  str
fund_house            str
aum_lakh_crore    float64
aum_crore           int64
num_schemes         int64
dtype: object

Missing Values
date              0
fund_house        0
aum_lakh_crore    0
aum_crore         0
num_schemes       0
dtype: int64

Duplicates
0

============================================================
SIP
============================================================

Data Types
month                            str
sip_inflow_crore               int64
active_sip_accounts_crore    float64
new_sip_accounts_lakh        float64
sip_aum_lakh_crore           float64
yoy_growth_pct               float64
dtype: object

Missing Values
month                         0
sip_inflow_crore              0
active_sip_accounts_crore     0
new_sip_accounts_lakh         0
sip_aum_lakh_crore            0
yoy_growth_pct               12
dtype: int64

Duplicates
0

============================================================
CATEGORY
============================================================

Data Types
month                   str
category                str
net_inflow_crore    float64
dtype: object

Missing Values
month               0
category            0
net_inflow_crore    0
dtype: int64

Duplicates
0

============================================================
FOLIO
============================================================

Data Types
month                      str
total_folios_crore     float64
equity_folios_crore    float64
debt_folios_crore      float64
hybrid_folios_crore    float64
others_folios_crore    float64
dtype: object

Missing Values
month                  0
total_folios_crore     0
equity_folios_crore    0
debt_folios_crore      0
hybrid_folios_crore    0
others_folios_crore    0
dtype: int64

Duplicates
0

============================================================
PERFORMANCE
============================================================

Data Types
amfi_code               int64
scheme_name               str
fund_house                str
category                  str
plan                      str
return_1yr_pct        float64
return_3yr_pct        float64
return_5yr_pct        float64
benchmark_3yr_pct     float64
alpha                 float64
beta                  float64
sharpe_ratio          float64
sortino_ratio         float64
std_dev_ann_pct       float64
max_drawdown_pct      float64
aum_crore               int64
expense_ratio_pct     float64
morningstar_rating      int64
risk_grade                str
dtype: object

Missing Values
amfi_code             0
scheme_name           0
fund_house            0
category              0
plan                  0
return_1yr_pct        0
return_3yr_pct        0
return_5yr_pct        0
benchmark_3yr_pct     0
alpha                 0
beta                  0
sharpe_ratio          0
sortino_ratio         0
std_dev_ann_pct       0
max_drawdown_pct      0
aum_crore             0
expense_ratio_pct     0
morningstar_rating    0
risk_grade            0
dtype: int64

Duplicates
0

============================================================
TRANSACTIONS
============================================================

Data Types
investor_id               str
transaction_date          str
amfi_code               int64
transaction_type          str
amount_inr              int64
state                     str
city                      str
city_tier                 str
age_group                 str
gender                    str
annual_income_lakh    float64
payment_mode              str
kyc_status                str
dtype: object

Missing Values
investor_id           0
transaction_date      0
amfi_code             0
transaction_type      0
amount_inr            0
state                 0
city                  0
city_tier             0
age_group             0
gender                0
annual_income_lakh    0
payment_mode          0
kyc_status            0
dtype: int64

Duplicates
0

============================================================
PORTFOLIO
============================================================

Data Types
amfi_code              int64
stock_symbol             str
stock_name               str
sector                   str
weight_pct           float64
market_value_cr      float64
current_price_inr    float64
portfolio_date           str
dtype: object

Missing Values
amfi_code            0
stock_symbol         0
stock_name           0
sector               0
weight_pct           0
market_value_cr      0
current_price_inr    0
portfolio_date       0
dtype: int64

Duplicates
0

============================================================
BENCHMARK
============================================================

Data Types
date               str
index_name         str
close_value    float64
dtype: object

Missing Values
date           0
index_name     0
close_value    0
dtype: int64

Duplicates
0

# Analysing and Exploring fund_master.csv

In [13]:
# Cell 8 — Fund Master Analysis
fund_master = loaded_data["fund_master"]

fund_master.head()

,amfi_code,fund_house,scheme_name,category,sub_category,plan,launch_date,benchmark,expense_ratio_pct,exit_load_pct,min_sip_amount,min_lumpsum_amount,fund_manager,risk_category,sebi_category_code
0,119551,SBI Mutual Fund,SBI Bluechip Fund - Regular Plan - Growth,Equity,Large Cap,Regular,2006-02-14,NIFTY 100 TRI,1.54,1.0,500,1000,Sohini Andani,Moderate,EC01
1,119552,SBI Mutual Fund,SBI Bluechip Fund - Direct Plan - Growth,Equity,Large Cap,Direct,2013-01-01,NIFTY 100 TRI,0.66,1.0,500,1000,Sohini Andani,Moderate,EC01
2,119598,SBI Mutual Fund,SBI Small Cap Fund - Regular Plan - Growth,Equity,Small Cap,Regular,2009-09-09,BSE 250 SmallCap TRI,1.43,1.0,500,1000,R. Srinivasan,Very High,EC03
3,119599,SBI Mutual Fund,SBI Small Cap Fund - Direct Plan - Growth,Equity,Small Cap,Direct,2013-01-01,BSE 250 SmallCap TRI,0.72,1.0,500,1000,R. Srinivasan,Very High,EC03
4,119120,SBI Mutual Fund,SBI Magnum Gilt Fund - Regular Plan - Growth,Debt,Gilt,Regular,2000-12-30,CRISIL Dynamic Gilt Index,0.77,0.0,500,1000,Dinesh Ahuja,Low,DC02

In [14]:
# Cell 9 — Unique Fund Houses
sorted(
    fund_master["fund_house"].unique()
)

['Aditya Birla Sun Life MF',
 'Axis Mutual Fund',
 'DSP Mutual Fund',
 'HDFC Mutual Fund',
 'ICICI Prudential MF',
 'Kotak Mahindra MF',
 'Mirae Asset MF',
 'Nippon India MF',
 'SBI Mutual Fund',
 'UTI Mutual Fund']

In [15]:
# Cell 10 — Categories
sorted(
    fund_master["category"].unique()
)

['Debt', 'Equity']

In [16]:
# Cell 11 — Sub Categories
if "sub_category" in fund_master.columns:
    sorted(
        fund_master["sub_category"].unique()
    )

In [17]:
# Cell 12 — Risk Grades
if "risk_grade" in fund_master.columns:

    fund_master["risk_grade"] \
        .value_counts()

In [18]:
# Cell 13 — Fund House Distribution
fund_master["fund_house"] \
    .value_counts()

fund_house
SBI Mutual Fund             5
HDFC Mutual Fund            5
ICICI Prudential MF         5
Nippon India MF             5
Kotak Mahindra MF           4
Axis Mutual Fund            4
Aditya Birla Sun Life MF    3
UTI Mutual Fund             3
Mirae Asset MF              3
DSP Mutual Fund             3
Name: count, dtype: int64

In [19]:
# Cell 14 — AMFI Code Validation
fund_codes = set(
    loaded_data["fund_master"]["amfi_code"]
)

nav_codes = set(
    loaded_data["nav_history"]["amfi_code"]
)

missing_codes = fund_codes - nav_codes

print("Fund Master Codes :", len(fund_codes))
print("NAV Codes         :", len(nav_codes))
print("Missing Codes     :", len(missing_codes))

Fund Master Codes : 40
NAV Codes         : 40
Missing Codes     : 0

In [20]:
# Cell 15 — Missing AMFI Codes
missing_codes

set()

In [24]:
# Cell 16 — Data Quality Report
quality_report = []

for name, df in loaded_data.items():

    quality_report.append({
        "Dataset":    name,
        "Rows":       df.shape[0],
        "Columns":    df.shape[1],
        "Missing":    df.isnull().sum().sum(),
        "Duplicates": df.duplicated().sum()
    })

quality_df = pd.DataFrame(
    quality_report
)

quality_df

        Dataset   Rows  Columns  Missing  Duplicates
0   fund_master     40       15        0           0
1   nav_history  46000        3        0           0
2           aum     90        5        0           0
3           sip     48        6       12           0
4      category    144        3        0           0
5         folio     21        6        0           0
6   performance     40       19        0           0
7  transactions  32778       13        0           0
8     portfolio    322        8        0           0
9     benchmark   8050        3        0           0

In [23]:
# Cell 17 — Save Data Quality Report
quality_df.to_csv(
    REPORT_DIR / "data_quality_report.csv",
    index=False
)

print("Data Quality Report Saved")

Data Quality Report Saved